
export default [
    {
        "entryId": 3420,
        "datePosted": "2022-06-22T11:48:02.000+00:00",
        "lastUpdated": "2022-06-22T11:48:02.000+00:00",
        "userId": 1,
        "userName": "Chris",
        "allowComments": false,
        "syndicate": false,
        "title": "Building Cornering Skills",
        "imageFileName": null,
        "imageFileType": null,
        "intro": "<iframe width=\"630\" height=\"354\"\r\nsrc=\"https://www.youtube-nocookie.com/embed/WPjJW0afKuw\"\r\ntitle=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer;\r\nautoplay; clipboard-write; encrypted-media; gyroscope;\r\npicture-in-picture\" allowfullscreen></iframe>\r\n\r\n\r\n<p> I did\r\n    a <a href=\"https://www.youtube.com/watch?v=iH3swh6FNeU&list=PLxYelmw06qAV9a27sJIl7UIARS0MmKEJY\">series\r\n    of \"Race Notes\" videos</a> covering my 2021 Over the Hump season,\r\n    and trying to note what I could do better. \r\n</p>\r\n\r\n<p> One thing that was really clear in 2021, and again this year in\r\n    2022, was that I need to improve my cornering, especially on loose\r\n    trail. So I've been practicing.\r\n</p>\r\n\r\n<p> My favorite video on cornering a mountain bike\r\n    is <a href=\"https://youtu.be/8y6ocZHpLoE\">this one by The Loam\r\n    Ranger</a>. I love that he establishes that leaning\r\n    the <em>bike</em> is key. \r\n</p>\r\n\r\n<p> Focusing on that really helped. But something still wasn't\r\n    clicking. The video above on cornering motorcycles really helped.\r\n</p>\r\n\r\n<p> What I noticed was that the rider was setting up for the U-turn by\r\n    shifting his hips to the outside of the turn. Basically, for a\r\n    left turn, he'd put his left butt cheek on the saddle, and\r\n    vice-versa for the right.\r\n</p>\r\n\r\n<p> When I tried that, a few things happened naturally:\r\n</p>\r\n\r\n<ul>\r\n    <li> I made more space for my saddle to lean into the turn.\r\n    </li>\r\n    <li> Rather than trying to drop my outside foot all the way to the\r\n        \"6 o'clock\" position at the bottom of the stroke, I adopted a\r\n        stance with my inside foot <em>slightly</em> higher than my\r\n        outside foot, which I've heard called the \"60/40 stance\".\r\n    </li>\r\n    <li> That, in turn, let me lean the bike <em>much</em> more\r\n        easily, getting those all-important turning lugs planted in\r\n        the dirt.\r\n    </li>\r\n</ul>\r\n\r\n<p> And all of this felt <em>much</em> more natural than ever\r\n    before. I feel more secure in the turns, and it feels so much more\r\n    secure than ever before.\r\n</p>\r\n\r\n<p> And the proof is in the pudding. There were <em>so</em> many\r\n    moments during last night's race where I was clearly carrying more\r\n    momentum through turns than before. In places where I used to just\r\n    be part of the conga line going through a twisty section, I was\r\n    often picking up time on the riders around me.\r\n</p>\r\n\r\n<p> My training goals for the rest of 2022 boil down to:\r\n</p>\r\n\r\n<ol>\r\n    <li> get leaner (ideally, weight around 175#)\r\n    </li>\r\n    <li> build trail skills\r\n    </li>\r\n    <li> build my ability to sustain race pace with periodic 30- to\r\n        90-second punches at 400-500W.\r\n    </li>\r\n</ol>\r\n\r\n<p> It's really great to be making solid progress on #2 there.\r\n</p>",
        "body": null,
        "viaTitle": null,
        "viaText": null,
        "viaUrl": null,
        "tags": [],
        "comments": [],
        "attachments": [],
        "hasAttachments": false,
        "numComments": 0
    }, {
        "entryId": 3419,
        "datePosted": "2022-02-25T22:31:58.000+00:00",
        "lastUpdated": "2022-02-25T22:36:05.000+00:00",
        "userId": 1,
        "userName": "Chris",
        "allowComments": false,
        "syndicate": false,
        "title": "Executing on the Fat Loss Plan",
        "imageFileName": "20220225-garage.jpg",
        "imageFileType": "image",
        "intro": "<p> I've adjusted my training & nutrition to prioritize fat loss, and\r\n    it's working ever so gradually, just like it should. But man…\r\n    doing this The Right Way is... HARD.\r\n</p>\r\n\r\n\r\n<p> It's going well. I'm down ~10lbs over ~4 months. I spoke with a\r\n    dietitian & implemented a few of her recommendations:\r\n</p>\r\n\r\n<p> <b>less sugar/simple carbs</b>\r\n</p>\r\n\r\n<p> On days I don't ride, I've swapped my high-carb oatmeal breakfast\r\n    for scrambled eggs & a slice of toast. Snacks feature\r\n    veggies/hummus, etc.\r\n</p>\r\n\r\n<p> <b>prebiotics & probiotics, fiber</b>\r\n\r\n<p> I now supplement to support gut biome health:\r\n</p>\r\n\r\n<ul>\r\n    <li> breakfast: fiber supplement\r\n    </li> \r\n    <li> lunch: prebiotics\r\n    </li>\r\n    <li> dinner: probiotics\r\n</ul>\r\n\r\n<p> <b>more sleep</b>\r\n</p>\r\n\r\n<p> It's easy to stay up watching TV or playing games or\r\n    doomscrolling, and for me that results in ~6½hrs of sleep per\r\n    night. Getting in bed earlier & pushing that toward 7½hrs has\r\n    really helped.\r\n</p>\r\n\r\n<p> <b>NOPE: more veggies</b>\r\n</p>\r\n\r\n<p> I've gotten some more veggies into my diet, but not nearly\r\n    enough. There's 100% room for improvement here.\r\n</p>\r\n\r\n\r\n<p> I've also made some adjustments to my training to prioritize fat\r\n    loss.\r\n</p>\r\n\r\n<p> <b>consistently make time for weight training</b>\r\n</p>\r\n\r\n<p> My love of biking often leads me to want to skip my Thursday's\r\n    barbell session so I can give Friday's ride my all. But for me,\r\n    consistently doing SOMETHING every day is FAR more conducive to\r\n    fat loss than going hard every other day.\r\n</p>\r\n\r\n<p> I have to remember that a new PR is nice, but what I really want\r\n    is a whole <em>stack</em> of new PRs as payoff for dropping this\r\n    extra fat I'm carrying around. I'll be healthier\r\n    &amp; <em>significantly</em> faster if I drop the extra weight.\r\n</p>\r\n\r\n\r\n<p> <b>on-bike fueling</b>\r\n</p>\r\n\r\n<p> I usually put Gu Roctane in both bottles. That keeps me fueled\r\n    through the end of the ride, which is good for recovery. But it\r\n    also means more sugar in my system than I really need. So now it's\r\n    1 bottle of Roctane, 1 of water.\r\n</p>\r\n\r\n<p> That cuts just 250 Cal from my daily intake, and my rides\r\n    typically burn 800-1400 Cal. But I find that\r\n    cutting <em>sugar</em> in particular has an outsized effect on\r\n    body composition.\r\n</p>\r\n\r\n\r\n<p> <b>What's the Goal?</b>\r\n\r\n<p> I'm starting to notice clothes fitting differently, and\r\n    I'm <em>maybe</em> starting to notice that I'm feelign stronger on\r\n    the bike. So that's encouraging. I'm down from ~205# to reliably\r\n    under ~195#, and I'd love to get back down under 180#, where I was\r\n    in April of 2019. I felt <em>great</em> back then, and wasn't\r\n    strugling or pushing myself to maintain that.\r\n</p>\r\n\r\n\r\n",
        "body": null,
        "viaTitle": null,
        "viaText": null,
        "viaUrl": null,
        "tags": [],
        "comments": [],
        "attachments": [{
            "attachmentId": 2913,
            "entryId": 3419,
            "isGalleryImage": false,
            "activityId": null,
            "fileName": "20220225-garage.jpg",
            "mimeType": null,
            "fileType": "image",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2022-02-25T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "Garage",
            "description": null,
            "isMap": false
        }],
        "hasAttachments": true,
        "numComments": 0
    }, {
        "entryId": 3418,
        "datePosted": "2022-02-03T22:38:35.000+00:00",
        "lastUpdated": "2022-02-03T22:40:27.000+00:00",
        "userId": 1,
        "userName": "Chris",
        "allowComments": false,
        "syndicate": false,
        "title": "2022 OtH Winter Series #2 (Int, 40-49): 11th",
        "imageFileName": "oth-20220229.jpg",
        "imageFileType": "image",
        "intro": "<p> I didn't catch the first Winter Series race, but I was determined\r\n    not to miss the second. My result wasn't great, but I had fun, and\r\n    it renewed my motivation to trim off the fat that I've gained\r\n    ever-so-slowly over the last couple of years. \r\n</p>\r\n\r\n<p> I'm looking forward to race #3 on Feb 26, and I'm determined to\r\n    line up for the Summer Series on May 3 leaner & fitter than I've\r\n    been in years.\r\n</p>\r\n",
        "body": null,
        "viaTitle": null,
        "viaText": null,
        "viaUrl": null,
        "tags": [],
        "comments": [],
        "attachments": [{
            "attachmentId": 2912,
            "entryId": 3418,
            "isGalleryImage": false,
            "activityId": null,
            "fileName": "oth-20220229.jpg",
            "mimeType": null,
            "fileType": "image",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2022-02-03T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "OTH 2022/02/29",
            "description": null,
            "isMap": false
        }],
        "hasAttachments": true,
        "numComments": 0
    }, {
        "entryId": 3417,
        "datePosted": "2021-12-23T13:04:14.000+00:00",
        "lastUpdated": "2021-12-23T15:32:51.000+00:00",
        "userId": 1,
        "userName": "Chris",
        "allowComments": false,
        "syndicate": false,
        "title": "Prioritizing Fat Loss",
        "imageFileName": "20211223-garage-bike.jpg",
        "imageFileType": "image",
        "intro": "<p> This winter, I'm finally doing what I said I need to do, and\r\n    focusing on getting leaner. The scale &amp; my body measurements\r\n    have been telling me for a couple of years that while\r\n    my <a href=\"archive/3402\">hypertrophy</a> block was\r\n    a <em>raging</em> success, it left me with extra fat that I never\r\n    managed to shed.\r\n</p>\r\n\r\n<p> Here's what seems to be working.\r\n</p>\r\n\r\n<p> <b>Daily Routine</b>\r\n</p>\r\n\r\n<ul>\r\n    <li> ~550Cal, high-carb breakfast of oatmeal, bagel, etc. (I've been enjoying <a href=\"https://www.foodnetwork.com/recipes/bijus-oatmeal-3048472\">Biju's Oatmeal</a>.)\r\n    </li>\r\n    <li> workout/ride (I fuel with Roctane mix, usually 1 bottle @ 250Cal)\r\n    </li>\r\n    <li> post-workout protein shake (protein powder, milk) (~360Cal)\r\n    </li>\r\n    <li> light lunch (~300Cal)\r\n    </li>\r\n    <li> RIDE DAYS: snack (~250Cal) &amp; coffee (~80Cal)\r\n    </li>\r\n    <li> LIFTING DAYS: just coffee\r\n    </li>\r\n</ul>\r\n\r\n<p> <b>Weekly Routine</b>\r\n</p>\r\n\r\n<ul>\r\n    <li> MON: Ride 90min\r\n    </li>\r\n    <li> TUES: Strength &amp; Conditioning\r\n    </li>\r\n    <li> WED: Ride 90min\r\n    </li>\r\n    <li> THURS: Strength &amp; Conditioning\r\n    </li>\r\n    <li> FRI: Ride 2hrs\r\n    </li>\r\n</ul>\r\n\r\n<p> <b>Strength &amp; Conditioning</b>\r\n</p>\r\n\r\n<p> I'm doing a 10min warmup run or KB session, then the barbell\r\n    complex from Dan John's <a href=\"archive/3402\">Mass Made\r\n        Simple</a>.\r\n</p>\r\n\r\n\r\n<ul>\r\n    <li>5 rounds\r\n    </li>\r\n    <li> 5 reps each movement\r\n    </li>\r\n    <li> each round should take under 1:45\r\n    </li>\r\n    <li> rest 1:30 between rounds\r\n    </li>\r\n    <li> movements:\r\n        <ol>\r\n            <li> bent row </li>\r\n            <li> power clean </li>\r\n            <li> front squat </li>\r\n            <li> military press </li>\r\n            <li> back squat </li>\r\n            <li> Romanian deadlift </li>\r\n        </ol>\r\n    </li>\r\n</ul>\r\n\r\n<p> I'm currently doing this with 85# on the bar, and that's feeling\r\n    just a hair light, so next week will be at 90#. \r\n</p>\r\n\r\n<p> Add more weight when you're consistently under the 1:45 mark for\r\n    each round. If you want to go up in 10# increments, the first\r\n    workout with the new load should have rests of 2:00 between\r\n    rounds. Trust me on that.\r\n</p>\r\n\r\n<p> This seems to be working. Over the last month or so, I've dropped\r\n    from ~205# to consistently weighing in around 199#.\r\n</p>\r\n\r\n<p> I was genuinely surprised to see that I'd\r\n    gotten <a href=\"archive/3389\">under 180#</a> back in 2019. No\r\n    wonder I was quicker back then.\r\n</p>\r\n\r\n<p> So far, this rhythm is letting me drop fat while still getting\r\n    quicker on the bike, which is ultimately my goal. I'll continue\r\n    this as long as it keeps working. I'll re-evaluate priorities when\r\n    I get back down under 190#. \r\n</p>\r\n",
        "body": null,
        "viaTitle": null,
        "viaText": null,
        "viaUrl": null,
        "tags": [],
        "comments": [],
        "attachments": [{
            "attachmentId": 2911,
            "entryId": 3417,
            "isGalleryImage": false,
            "activityId": null,
            "fileName": "20211223-garage-bike.jpg",
            "mimeType": null,
            "fileType": "image",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-12-23T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "Garage Gym",
            "description": null,
            "isMap": false
        }],
        "hasAttachments": true,
        "numComments": 0
    }, {
        "entryId": 3416,
        "datePosted": "2021-09-13T15:07:52.000+00:00",
        "lastUpdated": "2021-09-13T15:16:48.000+00:00",
        "userId": 1,
        "userName": "Chris",
        "allowComments": false,
        "syndicate": false,
        "title": "2021 OtH #4-8, Season Wrap-Up",
        "imageFileName": "oth-5-chris.jpg",
        "imageFileType": "image",
        "intro": "<p> Races 4-8 were a steady progression of feeling stronger &amp;\r\n    getting better results. Each week I did better &amp; better,\r\n    climbing from 18th to 13th, which is <em>great</em>. I only placed\r\n    16th overall, but that's to be expected when I spent the middle of\r\n    the series finishing around 20th each week.\r\n</p>\r\n\r\n<p> 8 individual races kind of blur together, but I <em>did</em> learn\r\n    plenty during this time.\r\n</p>\r\n\r\n<p> Initially, I was soft-pedaling into spots where I knew there would\r\n    be an accordion effect, thinking that I was saving energy. \"We're\r\n    all gonna be wheel-to-wheel in a second anyway,\" I'd think. And\r\n    then three riders would dive in ahead of me, which would hold me\r\n    up and/or push me off the fast line, and I'd come out the other\r\n    end of the accordion having surrendered 5 positions.\r\n</p>\r\n\r\n<p> In later races, I reframed the typical rhythm of open trail\r\n    punctuated by tight turns or bottlenecks. I relized that in a 40-\r\n    to 60-minute race, it's a sprint from start to finish. Saving\r\n    energy is <em>nice</em>, but you've gotta do\r\n    it <em>opportunistically</em> rather than <em>tactically</em>.\r\n</p>\r\n\r\n<p> Meaning: <em>if</em> someone is going a little faster than\r\n    you, <em>and</em> you can draft, then draft. But it's\r\n    almost <em>never</em> a good call to draft behind someone slower than\r\n    you in hopes of \"resting\" or \"recovering\".\r\n</p>\r\n\r\n<p> I worked on my cornering, and discovered that (possibly because of\r\n    the current state of my skills) I'm <em>far</em> smoother carrying\r\n    speed through corners if I <em>stand</em>.\r\n</p>\r\n\r\n<p> And I found that I can totally stand &amp; power up climbs &amp;\r\n    pass people, and that this works <em>much</em> better for me than\r\n    trying to sit &amp; spin.\r\n</p>\r\n\r\n<p> Between standing for power and standing through corners, my\r\n    approach to most of this race <em>completely</em> changed. I'd\r\n    brake late, carry speed through the corner (leaning the bike as\r\n    much as possible for more grip), then stay standing &amp; power\r\n    out, rinse &amp; repeat.\r\n</p>\r\n\r\n<p> And honestly, I think pushing myself each week did great things\r\n    for my fitness. Not only was I <em>performing</em> better each\r\n    week, I <em>felt</em> better after the race.\r\n</p>\r\n\r\n<p> I haven't seen my heart rate hit 185 BPM in a <em>long</em> time,\r\n    but it did duringing these races.\r\n</p>\r\n\r\n<h2>Take-Aways</h2>\r\n\r\n<p> Most of what I learned from the <a href=\"archive/3398\">2019 Over\r\n        the Hump series</a> served me well. A few additions:\r\n</p>\r\n\r\n<p> <b>Pass when you can:</b> the twists &amp; turns of this race\r\n    offer little windows where passing is possible. Make the most of\r\n    those opportunities. Pass, then use the course to defend your\r\n    position &amp; recoup for a few seconds, then go again.\r\n</p>\r\n\r\n<p> <b>Foam rolling:</b> foam rolling is <b>amazing</b> and completely\r\n    eliminated any need for Sudafed/NyQuil after races. Never even\r\n    thought to reach for them.\r\n</p>\r\n\r\n<p> <b>Base layer:</b> I have a\r\n    few <a href=\"https://www.pearlizumi.com/US/en/shop/men/baselayers/road/transfer_mesh_sleeveless_baselayer/p/11122106\">sleeveless\r\n        base layer tops</a>, and I'm now <em>religious</em> about wearing\r\n    them. Even on the hottest days on the race course, I felt like my\r\n    sweat was <em>actually cooling me</em> rather than just dripping off\r\n    or evaporating uselessly.\r\n</p>\r\n\r\n<p> <b>Bike fit:</b> after getting frustrated with lingering saddle\r\n    sores, I got a fit from <a href=\"http://boscobikefits.com/\">Bosco\r\n    Bike Fits</a>, and it was money <em>well</em> spent. My sores\r\n    disappeared as if they never existed, and have not returned.\r\n</p>\r\n\r\n<p> <b>Roctane Recovery Mix:</b> It's not cheap, but I really do love\r\n    it. Fantastic recharge after hard workouts. I ran out during the\r\n    last couple of races, and replaced it with a simple mix of protein\r\n    powder, milk, and chocolate syrup, and that seemed to get the job\r\n    done well enough.\r\n</p>\r\n\r\n",
        "body": null,
        "viaTitle": null,
        "viaText": null,
        "viaUrl": null,
        "tags": [],
        "comments": [],
        "attachments": [{
            "attachmentId": 2906,
            "entryId": 3416,
            "isGalleryImage": false,
            "activityId": "2021-08-18T01:05:42Z",
            "fileName": "20210817-oth5.gpx",
            "mimeType": null,
            "fileType": "map",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-09-13T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "OtH #5 (Intermediate, 40-49): 17th",
            "description": null,
            "isMap": true
        }, {
            "attachmentId": 2907,
            "entryId": 3416,
            "isGalleryImage": false,
            "activityId": null,
            "fileName": "20210824-oth6.gpx",
            "mimeType": null,
            "fileType": "map",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-09-13T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "OtH #6 (Intermediate, 40-49): 16th",
            "description": null,
            "isMap": true
        }, {
            "attachmentId": 2908,
            "entryId": 3416,
            "isGalleryImage": false,
            "activityId": "2021-09-01T01:13:33Z",
            "fileName": "20210831-oth7.gpx",
            "mimeType": null,
            "fileType": "map",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-09-13T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "OtH #7 (Intermediate, 40-49): 15th",
            "description": null,
            "isMap": true
        }, {
            "attachmentId": 2909,
            "entryId": 3416,
            "isGalleryImage": false,
            "activityId": "2021-09-08T01:12:09Z",
            "fileName": "20210907-oth8.gpx",
            "mimeType": null,
            "fileType": "map",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-09-13T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "OtH #8 (Intermediate, 40-49): 13th",
            "description": null,
            "isMap": true
        }, {
            "attachmentId": 2910,
            "entryId": 3416,
            "isGalleryImage": false,
            "activityId": null,
            "fileName": "oth-5-chris.jpg",
            "mimeType": null,
            "fileType": "image",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-09-13T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "Chris during 2021 OtH 5",
            "description": null,
            "isMap": false
        }],
        "hasAttachments": true,
        "numComments": 0
    }, {
        "entryId": 3415,
        "datePosted": "2021-09-09T16:13:58.000+00:00",
        "lastUpdated": "2021-09-09T16:13:58.000+00:00",
        "userId": 1,
        "userName": "Chris",
        "allowComments": false,
        "syndicate": false,
        "title": "Starting My 2022 Strength Build",
        "imageFileName": null,
        "imageFileType": null,
        "intro": "<p> The 2021 <a href=\"https://raceoc.com/\">Over the Hump</a> series\r\n    wrapped up on Tuesday evening, and I'll for sure have more to say\r\n    about how that went.\r\n</p>\r\n\r\n<p> For now, though, I want to document my starting numbers for my\r\n    next training block.\r\n</p>\r\n\r\n<p> The general plan is to spend the next few months with the\r\n    following priorities:\r\n</p>\r\n\r\n\r\n<ol>\r\n    <li> get leaner\r\n    </li>\r\n    <li> get stronger\r\n    </li>\r\n    <li> don't lose on-bike fitness\r\n    </li>\r\n</ol>\r\n\r\n<p> <b>Current Measurements</b>\r\n</p>\r\n\r\n<p> The only metric here that I have any kind of goal for is my\r\n    weight. I'm <em>clearly</em> currently carrying more fat than I\r\n    need to, and some rough calculations indicate that getting down\r\n    around 15% body fat would put me right around <b>180#</b>. So\r\n    that's what I'm aiming for.\r\n</p>\r\n\r\n<p> <b><em>However.</em></b>\r\n</p>\r\n\r\n<p> If I arrive in February 2022 leaner & stronger, but weighing above\r\n    180#, that's absolutely <em>not</em> any kind of failure. That's\r\n    why I take my other starting measurements, so that I can put my\r\n    weight in context. If my weight holds steady, but my waist goes\r\n    down and my thighs &amp; hips get bigger, that's a win.\r\n</p>\r\n\r\n<p style=\"text-align: center\">\r\n    <table border=\"1\" cellspacing=\"0\">\r\n        <tr>\r\n            <th>weight</th>\r\n            <td>192.2#</td>\r\n        </tr>        \r\n        <tr>\r\n            <th>calf</th>\r\n            <td>16''</td>\r\n        </tr>        \r\n        <tr>\r\n            <th>thigh</th>\r\n            <td>25''</td>\r\n        </tr>        \r\n        <tr>\r\n            <th>hips</th>\r\n            <td>41''</td>\r\n        </tr>        \r\n        <tr>\r\n            <th>waist</th>\r\n            <td>39.5''</td>\r\n        </tr>        \r\n        <tr>\r\n            <th>chest</th>\r\n            <td>41''</td>\r\n        </tr>        \r\n        <tr>\r\n            <th>biceps</th>\r\n            <td>15.5''</td>\r\n        </tr>        \r\n    </table>\r\n</p>\r\n\r\n<p> <b>Strength Goals (5x5 max)</b>\r\n</p>\r\n\r\n<p> Some of these goals are within reach over the next few\r\n    months. Some are... not. But I'm noting my \"big picture\" goal\r\n    here, and I'll see how close I can get.\r\n</p>\r\n\r\n\r\n<p style=\"text-align: center\">\r\n    <table border=\"1\" cellspacing=\"0\">\r\n        <tr>\r\n            <th>Movement</th>\r\n            <th>Current</th>\r\n            <th>Goal</th>\r\n        </tr>\r\n        <tr>\r\n            <th>squat</th>\r\n            <td>215#</td>\r\n            <td>250#</td>\r\n        </tr>        \r\n        <tr>\r\n            <th>deadlift</th>\r\n            <td>225#</td>\r\n            <td>295#</td>\r\n        </tr>        \r\n        <tr>\r\n            <th>bench press</th>\r\n            <td>TBD</td>\r\n            <td>195#</td>\r\n        </tr>        \r\n        <tr>\r\n            <th>chin-up</th>\r\n            <td>1 rep</td>\r\n            <td>15 reps</td>\r\n        </tr>        \r\n        <tr>\r\n            <th>military press</th>\r\n            <td>65#</td>\r\n            <td>110#</td>\r\n        </tr>        \r\n    </table>\r\n</p>\r\n\r\n<p> More on how the second half of\r\n    the Over the Hump series went is on the way, and I'll be noting\r\n    progress on my strength build periodically.\r\n</p>\r\n",
        "body": null,
        "viaTitle": null,
        "viaText": null,
        "viaUrl": null,
        "tags": [],
        "comments": [],
        "attachments": [],
        "hasAttachments": false,
        "numComments": 0
    }, {
        "entryId": 3414,
        "datePosted": "2021-08-16T10:22:28.000+00:00",
        "lastUpdated": "2023-11-27T01:59:54.000+00:00",
        "userId": 1,
        "userName": "Chris",
        "allowComments": false,
        "syndicate": false,
        "title": "2021 OtH #2-4 (Intermediate, 40-49)",
        "imageFileName": "20210810-oth.jpg",
        "imageFileType": "image",
        "intro": "<p> Every movie has a moment where the characters are introduced, the\r\n    central plot is established, and everything after that proceeds\r\n    from what we already know. (A few twists & turns aside.)\r\n    It's <a href=\"https://www.braddailey.com/three-act-structure\">the\r\n    end of the beginning</a>.\r\n</p>\r\n\r\n<p> I kind of feel like Race #4 was that moment for the 2021 Over the\r\n    Hump race season. Everyone's been moved to their proper divisions,\r\n    consistent winners have established themselves, and now we're all\r\n    just racing for incremental week-over-week improvement.\r\n</p>\r\n\r\n<p> <a href=\"archive/3413\">I took 9th in my first race</a>, which felt\r\n    like a good start, but then finished 12th &amp; 22nd in the next 2\r\n    races. That prompted\r\n    some <a href=\"https://twitter.com/DeathB4Decaf/status/1422813392042090497\">re-evaluation</a>\r\n    of my goals and some investigation into how I slid 12 places in 15\r\n    days. The nutshell: a bunch of stronger riders either showed up,\r\n    or moved into Intermediate from other divisions.\r\n</p>\r\n\r\n<p> So, rather than looking at results, I looked at my time relative\r\n    to a rider who consistently finishes in the top 3 to get a sense\r\n    of how I was doing.\r\n</p>\r\n\r\n<p> In the first race, I finished ~1:30 behind him. In the second, I\r\n    was ~3:30 back. In the third, I was a miserable 4:40 off the pace.\r\n</p>\r\n\r\n<p> So, <em>both</em> things are true:\r\n</p>\r\n\r\n<ul>\r\n    <li> Riders stronger than me have joined my class\r\n    </li>\r\n    <li> I wasn't racing as well week-over-week.\r\n    </li>\r\n</ul>\r\n\r\n<p> After race #3, I had a couple of take-aways.\r\n</p>\r\n\r\n<p> It is <em>immensely</em> clear that my trail skills have\r\n    atrophied. I'm not <em>nearly</em> as comfortable on trails as I\r\n    used to be, especially if they're loose. During races, I can feel\r\n    the extra effort taking its toll.\r\n</p>\r\n\r\n<p> The little, punchy climbs that litter the OtH courses were killing\r\n    me. I needed to get used to holding pace while periodically\r\n    pushing over short rises.\r\n</p>\r\n\r\n<p> I'd also been following my TrainerRoad training plan, which\r\n    prescribed mostly rest between races, with an \"openers\" workout\r\n    the day before each race. I wondered how doing actual training\r\n    between races would affect my performance. (Both in terms of race\r\n    results, and whether I'd improve week-to-week.)\r\n</p>\r\n\r\n<p> So before race #4, I did some training rides during the week, and\r\n    moved them from power-based interval workouts done mostly on flats\r\n    to more race-specific stuff on trails.\r\n</p>\r\n\r\n<p> And honestly, that seemed to help a bit. For Race #4, I\r\n    was <em>much</em> better able to deal with the short rises.\r\n</p>\r\n\r\n<p> Race #4 was honestly pretty uneventful. I was able to match my PR on\r\n    the <a href=\"https://www.strava.com/segments/654882?filter=overall\">back\r\n        lot climb</a>, which makes me happy, and I felt like I improved\r\n    the way I'm riding the first ~10 minutes of the race: didn't\r\n    overcook the start, maintained position well, and got onto the\r\n    flats with my HR at ~165 BPM, which is <em>exactly</em> where I\r\n    want to be.\r\n</p>\r\n\r\n<p> I fumbled at least one place right at the end by not following\r\n    through over the top of the final climb. I had a gap on the rider\r\n    behind me, and I'd have kept it if I just pushed for another 5\r\n    seconds & gotten up to speed heading into the final 2:00 of the\r\n    race. I got passed with ~1:00 left to go, and that's entirely my\r\n    own doing. I did manage to <em>barely</em> hold off an attempt to\r\n    get past me right at the line.\r\n</p>\r\n\r\n<p> So, 4 races in, it's clear I've gotta work on three things, and\r\n    they're not subtle.\r\n</p>\r\n\r\n<p> First, I need to work on my cornering. I'm just bleeding time on\r\n    every single corner, and I absolutely <em>hate</em> my lack of\r\n    confidence in the turns. It's costing me time <em>and</em> fun.\r\n</p>\r\n\r\n<p> Second, I'm going to do some YouTube research and see how faster,\r\n    more experienced racers deal with short rises. (~5 seconds)\r\n    There's a definite art to carrying momentum &amp; using minimal\r\n    energy to maintain/regain speed.\r\n</p>\r\n\r\n<p> And third, I simply have to get <em>faster</em>. When I was 1:25\r\n    off the lead, I felt like better skills &amp; tactics might close\r\n    the gap. But I'm 4:00+ back now, and that's down to my legs. \r\n</p>\r\n\r\n<p> And finally, I have to accept that if I'm going to win in\r\n    Intermediate, let alone move up to Sport &amp; be competitive\r\n    there, I'm going to have to get leaner. So I'm working on that. \r\n</p>\r\n",
        "body": "",
        "viaTitle": null,
        "viaText": null,
        "viaUrl": null,
        "tags": [],
        "comments": [],
        "attachments": [{
            "attachmentId": 2897,
            "entryId": 3414,
            "isGalleryImage": false,
            "activityId": "2021-07-28T01:15:14Z",
            "fileName": "20210727-oth2.gpx",
            "mimeType": null,
            "fileType": "map",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-08-16T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "OtH #2 (Intermediate, 40-49): 12th",
            "description": null,
            "isMap": true
        }, {
            "attachmentId": 2898,
            "entryId": 3414,
            "isGalleryImage": false,
            "activityId": "2021-08-04T01:11:19Z",
            "fileName": "20210803-oth3.gpx",
            "mimeType": null,
            "fileType": "map",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-08-16T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "OtH #3 (Intermediate, 40-49): 22nd",
            "description": null,
            "isMap": true
        }, {
            "attachmentId": 2899,
            "entryId": 3414,
            "isGalleryImage": false,
            "activityId": "2021-08-11T00:17:14Z",
            "fileName": "20210810-oth4.gpx",
            "mimeType": null,
            "fileType": "map",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-08-16T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "OtH #4 (Intermediate, 40-49): 18th",
            "description": null,
            "isMap": true
        }, {
            "attachmentId": 2900,
            "entryId": 3414,
            "isGalleryImage": false,
            "activityId": null,
            "fileName": "20210810-oth.jpg",
            "mimeType": null,
            "fileType": "image",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-08-16T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "Me riding my bike",
            "description": null,
            "isMap": false
        }, {
            "attachmentId": 2902,
            "entryId": 3414,
            "isGalleryImage": false,
            "activityId": null,
            "fileName": "03OnlineCategoryResults-2021OTH2.pdf",
            "mimeType": null,
            "fileType": "document",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-08-16T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "Results: 2021 OTH #2",
            "description": null,
            "isMap": false
        }, {
            "attachmentId": 2903,
            "entryId": 3414,
            "isGalleryImage": false,
            "activityId": null,
            "fileName": "03OnlineCategoryResults-2021OTH3.pdf",
            "mimeType": null,
            "fileType": "document",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-08-16T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "Results: 2021 OTH #3",
            "description": null,
            "isMap": false
        }, {
            "attachmentId": 2904,
            "entryId": 3414,
            "isGalleryImage": false,
            "activityId": null,
            "fileName": "03OnlineCategoryResults-2021OTH4.pdf",
            "mimeType": null,
            "fileType": "document",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-08-16T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "Results: 2021 OTH #4",
            "description": null,
            "isMap": false
        }],
        "hasAttachments": true,
        "numComments": 0
    }, {
        "entryId": 3413,
        "datePosted": "2021-07-22T22:26:04.000+00:00",
        "lastUpdated": "2021-08-16T10:48:15.000+00:00",
        "userId": 1,
        "userName": "Chris",
        "allowComments": false,
        "syndicate": false,
        "title": "Over the Hump #1: 9th (Intermediate, 40-49)",
        "imageFileName": "20210720-oth1.gpx",
        "imageFileType": "map",
        "intro": "<p> After nearly two years, the Over the Hump Tuesday-night races are\r\n    back on the calendar. Instead of two six-week blocks with a hiatus\r\n    in between, it's a single eight-week series. I'd <em>love</em> to\r\n    see more racing, and a longer season, but after 22 months of\r\n    waiting, I'll take what I can get.\r\n</p>\r\n\r\n<p> My goals were super-simple: stay with the leaders as long as I\r\n    could, and race smart. I've been watching\r\n    a <em>lot</em> <a href=\"https://www.youtube.com/channel/UCIfRR1N2Gm1vjj9X955iWSQ\">race\r\n    tactics videos</a> on YouTube this year, so I like to think I'm a\r\n    smarter racer than I was two years ago.\r\n</p>\r\n\r\n<p> Because of some delays at the venue, organizers shortened the race\r\n    from three laps to two, which I was slightly bummed about. The\r\n    last lap is usually where I'm able to pick up a few places. And a\r\n    short race means a brutal pace I wasn't sure I could hang with.\r\n</p>\r\n\r\n<p> I got off the line clean, and everyone seemed to take their time\r\n    getting up to speed. I was with the leaders into the first turn,\r\n    and felt really solid. As we crested the top of the hill & headed\r\n    down to the road along Irvine Lake, gaps were forming and I was\r\n    crosseyed, but I had the leaders in sight & felt okay about my\r\n    position.\r\n</p>\r\n\r\n<p> I did my best to breathe &amp; conserve energy on the flats, but\r\n    the pace was still <em>super</em>-high, and as we came through the\r\n    park &amp; onto the \"back 40\" section, I'd been gapped pretty\r\n    good. I figured with just two laps in the race this was the best\r\n    time to do whatever passing I was going to manage, and started to\r\n    work my way up through the traffic.\r\n</p>\r\n\r\n<p> It was <em>amazing</em> to push along the flats solo at 280W, then\r\n    tuck in behind someone and watch that number drop to 170W without\r\n    losing <em>any</em> speed. \r\n</p>\r\n\r\n<p> The flat finished with that hard left up the nose &amp; into the\r\n    CX section. I decided not to burn my matches there, and I feel\r\n    like that's the smart move there. It's maybe a 30-second climb, so\r\n    going into the red just gains you <em>maybe</em> 5 seconds, which\r\n    can be made up with minimal fuss later. \r\n</p>\r\n\r\n<p> My trail skills are rusty after so much fire road riding in my\r\n    training, and the course was really loose &amp; dusty. So I feel\r\n    like the back section took more out of me than it should have. (Or\r\n    at least, more than it used to.) \r\n</p>\r\n\r\n<p> I headed into lap 2 with no clue what position I was in. I just\r\n    tried to remind myself that there was no point saving any matches,\r\n    and that I really had maybe 15 minutes of racing left. \r\n</p>\r\n\r\n<p> I managed to pick up a place coming through the park, and as I\r\n    headed into the \"Back 40\", I spotted a huge train motoring along\r\n    about 40m ahead. I've learned my lesson from so many crit videos,\r\n    and I know that I've gotta catch that.\r\n</p>\r\n\r\n<p> So catch it I did. I kept myself just shy of redlining, but\r\n    managed to join the back of that train &amp; get into that sweet,\r\n    sweet suction. I took a minute to rest, but realized that I had\r\n    one competitor just ahead, and another behind. \r\n</p>\r\n\r\n<p> The train started to split apart, so I jumped on my competitor's\r\n    wheel &amp; went with him for the rest of the flat section. A\r\n    glance back showed a nice gap, so I stopped looking for the guy\r\n    behind, and just focused on moving up.\r\n</p>\r\n\r\n<p> The guy I was following attacked up the nose climb, and I just\r\n    couldn't go. I hoped that if I could stay in striking distance I\r\n    could make up the time later in the lap, but after that he\r\n    was <em>gone</em>.\r\n</p>\r\n\r\n<p> I had a nice gap after the final climb, but didn't want to take\r\n    that for granted. And I'm glad I didn't. A guy in my division\r\n    wearing all black managed to sneak up &amp; passed me going into\r\n    the second-to-last corner. <em>Very</em> fortunately, there was a\r\n    guy in another division just ahead of us and we all hit that\r\n    corner at the same time. Mr. All-Black was forced to\r\n    go <em>outside</em> of the other guy, but I had space to\r\n    pull <em>inside</em> &amp; get past them both. I spun up the hill\r\n    as fast as I could &amp; held on for 9th place. \r\n</p>\r\n\r\n<p> (My GPS says I hit 130+ RPM there, which seems unlikely, but\r\n    matches my experience at the time of just spinning as fast as I\r\n    could.)\r\n</p>\r\n\r\n<p> I had high hopes for this race. I spent several months at the\r\n    beginning of 2020 <a href=\"archive/3402\">building muscle</a>, and\r\n    I've been pushing hard on the bike to build my fitness.\r\n</p>\r\n\r\n<p> Unfortunately, it looks like I've mostly just <em>maintained</em>,\r\n    rather than improved. That's... disappointing.\r\n</p>\r\n\r\n<p> On the other hand, I'll get to do <em>eight</em> races this year\r\n    instead of just four back in 2019, and I\r\n    improved <em>significantly</em> during those four races back\r\n    then. I'm hoping I can do likewise this year.\r\n</p>\r\n\r\n<p> So, goals for next week:\r\n</p>\r\n\r\n<ul>\r\n    <li> start harder- stay with the <em>leaders</em>. I'm not 100%\r\n        convinced this will get me my best possible results, but I\r\n        really do feel like at this race the top finishers pull away\r\n        quickly &amp; stay away.\r\n    </li>\r\n    <li> more burning matches, more coasting. I spent a <em>lot</em>\r\n        of time just above FTP, and that meant I had nothing when I\r\n        needed to push harder. I want to see what happens when I, for\r\n        example, start hard, then coast &amp; draft along the flats,\r\n        then attack up the nose, then recover in the CX section, then\r\n        attack up the longer climb, then coast through the\r\n        start/finish, etc. Might be a terrible idea. Dunno. I want to\r\n        find out.\r\n    </li>\r\n</ul>",
        "body": null,
        "viaTitle": null,
        "viaText": null,
        "viaUrl": null,
        "tags": [],
        "comments": [],
        "attachments": [{
            "attachmentId": 2901,
            "entryId": 3413,
            "isGalleryImage": false,
            "activityId": null,
            "fileName": "03OnlineCategoryResults-2021OTH1.pdf",
            "mimeType": null,
            "fileType": "document",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-08-16T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "Results: 2021 OTH #1",
            "description": null,
            "isMap": false
        }, {
            "attachmentId": 2905,
            "entryId": 3413,
            "isGalleryImage": false,
            "activityId": "2021-07-21T01:19:53Z",
            "fileName": "20210720-oth1.gpx",
            "mimeType": null,
            "fileType": "map",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-08-16T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "OtH #1 (Intermediate, 40-49): 9th",
            "description": null,
            "isMap": true
        }],
        "hasAttachments": true,
        "numComments": 0
    }, {
        "entryId": 3412,
        "datePosted": "2021-05-10T10:34:20.000+00:00",
        "lastUpdated": "2021-05-10T10:58:00.000+00:00",
        "userId": 1,
        "userName": "Chris",
        "allowComments": false,
        "syndicate": false,
        "title": "Training Update: Upgrades & Saddle Sores",
        "imageFileName": "20210508-seatpost.jpg",
        "imageFileType": "image",
        "intro": "<h3>Upgrades!</h3>\r\n\r\n<p> First, I got a Stages left-crank power meter for my mountain\r\n    bike. The change has been <em>phenomenal</em>. Instant feedback on\r\n    technique means I'm really focusing on getting <em>faster</em>\r\n    rather than just building aerobic capacity as a proxy for power\r\n    output.\r\n</p>\r\n\r\n<p> That set the stage for joining TrainerRoad's training program. So\r\n    far, that's been awesome. I'm <em>clearly</em> getting much\r\n    stronger & faster, and I like the variety it provides over\r\n    something like <em>Time-Crunched Training Protocol</em>. \r\n</p>\r\n\r\n<p> And I've upgraded GPS unit, replacing my old Garmin Edge 500 with\r\n    a new Edge 130 Plus. Wireless sync has been awesome, and the\r\n    screen is <em>so</em> much clearer. Both units support structured\r\n    workout downloads from TrainierRoad, but the workout screen on the\r\n    130 Plus is <em>so</em> much better than what's available on the\r\n    500.\r\n</p>\r\n\r\n<p> I also decided to try using a base layer just for grins, and I'll\r\n    never go back to just a jersey. I'm using a Pearl Izumi sleeveless\r\n    mesh base layer, and it keeps the chilly days from\r\n    being <em>too</em> chilly, and noticeably helps make hot days\r\n    manageable as well.\r\n</p>\r\n\r\n<h3>Saddle Sores</h3>\r\n\r\n\r\n<p> I've never had trouble with saddles before this year. But now... I\r\n    do.\r\n</p>\r\n\r\n<p> I suspect that the biggest reason is that I've been\r\n    doing <em>much</em> more training (indeed, <em>most</em> of my\r\n    training) on flat fire roads along the Santa Anna River Trail. On\r\n    trails (where I did most of my riding until now), there's much\r\n    more weighting & unweighting the saddle, shifting positions, etc.\r\n</p>\r\n\r\n<p> Whatever the reason, saddle sores have been a persistent problem\r\n    for me for the last few months. So far, I've been lucky. They\r\n    haven't caused any disruption in my training or gotten beyond\r\n    merely annoying. But they're not going away, and I want to get\r\n    that resolved <em>before</em> it becomes a real problem.\r\n</p>\r\n\r\n<p> On the calendar, the next two weeks are rest & prep for a race in\r\n    Big Bear followed by a recovery week. So the plan is already\r\n    calling for very little time on the bike with lots of rest, and\r\n    workouts to maintain fitness rather than build it.\r\n</p>\r\n\r\n<p> I won't be doing the Big Bear race, so I'm going to take advantage\r\n    of that low volume to get some extra rest &amp; minimize my time\r\n    in the saddle. I'm hoping that doing just 2-3hrs over the next\r\n    couple of weeks will let my sores heal completely.\r\n</p>\r\n\r\n<p> I've also ordered a new seatpost that will give me more fine-tuned\r\n    tilt & setback options, and I have a new saddle with a slightly\r\n    wider body & more padding that I <em>hope</em> will help spread\r\n    some of the pressure & minimize hip rocking.\r\n</p>\r\n\r\n<p> And finally, once I'm healed I'm going to book a bike fit\r\n    at <a href=\"http://boscobikefits.com/\">Bosco Bike Fits</a> to get\r\n    my bike fit nailed down properly. I've never had a proper bike\r\n    fit, and I like to think that if I had, I'd wouldn't be dealing\r\n    with this now.\r\n</p>\r\n",
        "body": null,
        "viaTitle": null,
        "viaText": null,
        "viaUrl": null,
        "tags": [],
        "comments": [],
        "attachments": [{
            "attachmentId": 2894,
            "entryId": 3412,
            "isGalleryImage": false,
            "activityId": null,
            "fileName": "20210508-seatpost.jpg",
            "mimeType": null,
            "fileType": "image",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-05-10T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "Seatpost",
            "description": null,
            "isMap": false
        }],
        "hasAttachments": true,
        "numComments": 0
    }, {
        "entryId": 3411,
        "datePosted": "2021-01-04T11:39:08.000+00:00",
        "lastUpdated": "2021-01-28T14:06:03.000+00:00",
        "userId": 1,
        "userName": "Chris",
        "allowComments": false,
        "syndicate": false,
        "title": "2021 Goals, Recovery Methods",
        "imageFileName": "20210104-garage-bike.jpg",
        "imageFileType": "image",
        "intro": "<p> I've plotted a rough training outline for 2021, with the <em>Over\r\n    the Hump</em> races as B races, and some more classic style race\r\n    series on the radar as possibilities for A races if/when racing\r\n    resumes.\r\n</p>\r\n    \r\n<p> My goal for 2021 is to get on the podium as\r\n    an <em>Intermediate</em> racer, and set the stage for a move up\r\n    to <em>Sport</em> in 2022.\r\n</p>\r\n\r\n<p> For now, I'm using Strava's workouts (based on\r\n    Charmichael's <em>Time-Crunched Training Protocol</em>), and\r\n    making solid progress. Two-hour rides at 140 BPM feel easy, 150\r\n    BPM feels normal, and I'm doing intervals at 155-165 BPM to push\r\n    my FTP up. \r\n</p>\r\n\r\n<p> It's been a <em>long</em> time since I did real climbing repeats\r\n    at 170+ BPM, so my climbing is garbage at the moment. Looking to\r\n    get that back in order by April or so.\r\n</p>\r\n\r\n<p> I've ordered a power meter, and I'm planning to start with\r\n    TrainerRoad once that's fitted &amp; working, which I think will\r\n    really help me make better use of my training time.\r\n</p>\r\n\r\n<p> And I've started doing a few things that are <em>really</em>\r\n    helping recovery &amp; getting more out of my workouts.\r\n</p>\r\n\r\n<dl>\r\n    <dt> Fueling During the Workout </dt>\r\n    <dd>\r\n        <p> I've been fueling with Gu Roctane during my workouts, which\r\n            has made a <em>noticeable</em> difference in how I feel in the\r\n            second hour, especially when I need top-end power.\r\n        </p>\r\n        <ul>\r\n            <li> 1 bottle Roctane, 1 bottle water\r\n            </li>\r\n            <li> drink &frac12; bottle every 30 minutes\r\n            </li>\r\n            <li> finish the Roctane 30 minutes before the end of the ride\r\n            </li>\r\n        </ul>\r\n    </dd>\r\n\r\n    <dt> Recovery Drink After the Workout </dt>\r\n    <dd>\r\n        <p> I've been taking BCAAs &amp; water for years. A full\r\n            recovery drink is better. Gu Roctane Recovery\r\n            Mix, <em>or</em> a basic chocolate milk &amp; protein\r\n            shake:\r\n        </p>\r\n\r\n        <ul>\r\n            <li> 8 oz milk\r\n            </li>\r\n            <li> 1 scoop (25g) protein \r\n            </li>\r\n            <li> chocolate syrup to taste (~2tbsp)\r\n            </li>\r\n        </ul>\r\n    </dd>\r\n\r\n    <dt> Stretching &amp; Foam Rolling </dt>\r\n    <dd>\r\n        <p> I usually do this at night, immediately after doing my\r\n            nightly housework so I'm warm &amp; moving before I start.\r\n        </p>\r\n        \r\n        <ul>\r\n            <li> some version of my usual <a href=\"archive/2889\">stretching sequence</a>\r\n            </li>\r\n            <li> some strap-assisted work on hamstring &amp; hip mobility\r\n            </li>\r\n            <li> short foam rolling session for legs &amp; glutes,\r\n                focusing on slowly rolling toward my torso\r\n            </li>\r\n            <li> I sleep better when I do this- my legs are more relaxed &amp; I don't feel that \"gotta stretch\" feeling.\r\n            </li>\r\n            <li> I move around much more easily, especially getting up/down off the ground.\r\n            </li>\r\n            <li> I feel <em>noticeably</em> fresher the next day. No leftover stiffness or soreness.\r\n            </li>\r\n        </ul>\r\n    </dd>\r\n\r\n    <dt> Vitamins &amp; Krill Oil </dt>\r\n    <dd> \r\n        <p> I'm still doing my usual dinner-time supplementation:\r\n        </p>\r\n\r\n        <ul>\r\n            <li> 1 multivitamin\r\n            </li>\r\n            <li> 1 vitamin D\r\n            </li>\r\n            <li> 3 capsules krill oil\r\n            </li>\r\n        </ul>\r\n    </dd>\r\n\r\n    <dt> Focus on Sleep </dt>\r\n    <dd>\r\n        <p> Dan John said it well: \"Recovery = <em>Sleep</em>. Everything else is FOMO.\"\r\n        </p>\r\n        <ul>\r\n            <li> I make sure I get 7+ hours every night. 8+ as much as possible.\r\n            </li>\r\n            <li> I now use a device called a Smart Nora to eliminate\r\n                snoring, which helps my wife sleep, which in turn\r\n                means I'm not catching elbows in the middle of the\r\n                night.\r\n            </li>\r\n            <li> I nap when I need to, and focus on getting to bed at\r\n                a normal time the following night.\r\n            </li>\r\n        </ul>\r\n    </dd>\r\n\r\n</dl>\r\n\r\n",
        "body": null,
        "viaTitle": null,
        "viaText": null,
        "viaUrl": null,
        "tags": [],
        "comments": [],
        "attachments": [{
            "attachmentId": 2892,
            "entryId": 3411,
            "isGalleryImage": false,
            "activityId": null,
            "fileName": "20210104-garage-bike.jpg",
            "mimeType": null,
            "fileType": "image",
            "userId": 1,
            "userName": "Chris",
            "datePosted": "2021-01-04T00:00:00.000+00:00",
            "dateTaken": null,
            "title": "Garage",
            "description": null,
            "isMap": false
        }],
        "hasAttachments": true,
        "numComments": 0
    }
];

